---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
# baseurl: "http://127.0.0.1:8080"
baseurl: "http://www.asdrubalivan.com"
title: "Asdrubal's Blog"
canonifyurls: true
params:
  twitter : "asdrubalivan"
  github  : "asdrubalivan"
  facebook  : "asdrubalivan"
  linkedin  : "asdrubalivan"

